### ISSUE TITLE
Update install scripts

### ISSUE THREAD

**Issue by codesalad** [vwigmore/PlebNet#22]
In file `create_child.sh` for example
```
...
sshpass -p${PASSWORD} ssh -o StrictHostKeyChecking=no root@${IP} 'mkdir -p data/; mkdir -p .config/; mkdir -p .electrum/wallets/; mkdir -p .Tribler/wallet/'
...
```

`StrictHostKeyChecking=no` has **inconsistent** behaviour (at least on my vps).

Add the following to all those `ssh/sshpass` commands: `
```
-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
```

**Comment by codesalad** [comment]
This is taken care of in branch: [update_install_scripts](https://github.com/vwigmore/PlebNet/tree/update_install_scripts)

Current issues fixed:
*  changed host key checking => added `-o UserKnownHostsFile=/dev/null` to `create_child.sh`
*  install openssl & ca-certificates (unable to git clone - probably issue with minimal containers) => added
```
    apt-get install -y openssl && \
    apt-get install -y ca-certificates'
```
to `create_child`
* deleted branch names (plebnet) in `git clone` command => changed to `update_install_scripts`, will need to be **master** eventually

* Not sure: `create_child.sh` checks for `Child_DNA.json` and exits with error if not found, but if you want to run it from scratch, you'd have to either run plebnet and everything or make the file yourself. Changed to:

```
echo "Copying DNA"
if [ ! -e ${CHILD_DNA_FILE} ]; then
    echo "File $CHILD_DNA_FILE not found"
else
    sshpass -p${PASSWORD} scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${CHILD_DNA_FILE} root@${IP}:${DNA_FILE}
fi
```

This ignores the DNA if it's not found, so it just creates one for itself on the VPS. **Does this affect anything else?**

* Changed the Cloudomate repo to mine (master)

**Comment by codesalad** [comment]
**Debian 8.0 standard:**
**Tribler:**
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 450, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 486, in getUsage
    for (cmd, short, parser, desc) in self.subCommands:
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 621, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 209, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 167, in getCache
    provider = pluginModule.load()
  File "/usr/lib/python2.7/dist-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 242, in _importAndCheckStack
    return __import__(importName)
  File "/root/PlebNet/tribler/twisted/plugins/tunnel_helper_plugin.py", line 25, in <module>
    from Tribler.Core.Session import Session
  File "/root/PlebNet/tribler/Tribler/Core/Session.py", line 18, in <module>
    import Tribler.Core.permid as permid_module
  File "/root/PlebNet/tribler/Tribler/Core/permid.py", line 10, in <module>
    from Tribler.pyipv8.ipv8.keyvault.private.libnaclkey import LibNaCLSK
  File "/root/PlebNet/tribler/Tribler/pyipv8/ipv8/keyvault/private/libnaclkey.py", line 1, in <module>
    import libnacl
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 83, in <module>
    nacl = _get_nacl()
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 81, in _get_nacl
    raise OSError(msg)
exceptions.OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.23, libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4, 
```

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 450, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 486, in getUsage
    for (cmd, short, parser, desc) in self.subCommands:
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 621, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 209, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 167, in getCache
    provider = pluginModule.load()
  File "/usr/lib/python2.7/dist-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/root/PlebNet/tribler/twisted/plugins/tunnel_helper_plugin.py", line 25, in <module>
    from Tribler.Core.Session import Session
  File "/root/PlebNet/tribler/Tribler/Core/Session.py", line 20, in <module>
    from Tribler.Core.APIImplementation.LaunchManyCore import TriblerLaunchMany
  File "/root/PlebNet/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 43, in <module>
    from Tribler.pyipv8.ipv8.keyvault.private.m2crypto import M2CryptoSK
  File "/root/PlebNet/tribler/Tribler/pyipv8/ipv8/keyvault/private/m2crypto.py", line 6, in <module>
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature
exceptions.ImportError: No module named utils
```

As far as the other modules, PlebNet, Electrum and Cloudomate are installed correctly.

**Comment by codesalad** [comment]
Fixed for Debian 8, pyopenssl needed to be installed before libsodium modules. Installed libsodium with: `apt-get install libsodium-dev`. The `&&` sign in `apt-get update && apt-get install libsodium-dev` caused `libsodium-dev` to not install whenever a source was not found.

**Comment by codesalad** [comment]
(Changed label because this was not as minor as I thought)
